name: ion_flutter_example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_icons: ^1.0.0
  flutter_ion: ^0.2.2
  shared_preferences: ^0.5.12+4


  get: ^3.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
